//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.07.03 at 02:15:32 PM JST 
//


package jp.jizai.sample.jaxb.datetime.model;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the jp.jizai.sample.jaxb.datetime.model package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: jp.jizai.sample.jaxb.datetime.model
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DateTestModel4 }
     * 
     */
    public DateTestModel4 createDateTestModel4() {
        return new DateTestModel4();
    }

    /**
     * Create an instance of {@link DateTestModel3 }
     * 
     */
    public DateTestModel3 createDateTestModel3() {
        return new DateTestModel3();
    }

    /**
     * Create an instance of {@link DateTestModel2 }
     * 
     */
    public DateTestModel2 createDateTestModel2() {
        return new DateTestModel2();
    }

    /**
     * Create an instance of {@link DateTestModel1 }
     * 
     */
    public DateTestModel1 createDateTestModel1() {
        return new DateTestModel1();
    }

}
